### ISSUE TITLE
во славу модного кода #1

### ISSUE THREAD

**Issue by MarsiBarsi** [LuckyWasTaken/huffman-encoder#1]
давай ретурнить с кодом 1 сразу, если стрим закрыт

```
if (!input.is_open())
{
    cout << "Unable to open file";
    return 1;
}

char c;
while (input.get(c))
...
```
else писать не нужно -> код не такой глубокий получается и легче читается

**Comment by LuckyWasTaken** [comment]
Да, звучит как правильная вещь. Сам пр сделаешь или мне быстро накидать?

**Comment by MarsiBarsi** [comment]
> Да, звучит как правильная вещь. Сам пр сделаешь или мне быстро накидать?

поправь ты, а то у меня сейчас нет возможности :/

**Comment by LuckyWasTaken** [comment]
Понял принял

**Comment by LuckyWasTaken** [comment]
Сказано сделано!
